version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: pkozlov
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: django_db
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always

  server:
    image: pavkozlov/blog_server:latest
    container_name: server
    ports:
      - 8000:8000
    environment:
      POSTGRES_HOST: db
    restart: always
    links:
      - db

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - server
    ports:
      - 80:8989